### ISSUE TITLE
python exception should be using traceback.format_exception(e)

### ISSUE THREAD

**Issue by rpcme** [aws-samples/aws-cloud9-bootstrapping-example#2]
**Describe the bug**
python exception should be using traceback.format_exception(e)
**To Reproduce**
1. Look at code
2. Note incorrect call for named exception

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rpcme** [comment]
or just format_exc() without the parameter

**Comment by couchgott** [comment]
i will look into that

**Comment by couchgott** [comment]
changed/added!
