### ISSUE TITLE
Delete stack does not work because there is no Delete event captured in the bootstrap hook

### ISSUE THREAD

**Issue by rpcme** [aws-samples/aws-cloud9-bootstrapping-example#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by couchgott** [comment]
closing due inactivity and lack of information in the issue
deletion tested and worked.
