### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by jinseo-jang** [aws-samples/aws-cloud9-bootstrapping-example#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Now`ExampleC9BootstrapInstanceLambdaFunction`needs to be improved in error handling. For instance, when error happens in the part of `try`, `cfnresponse.send`doesn't throw Failure message to Cloudformation so Cloudformation ends up hang status. 
So I would recommend improvement like this.

```python
status = cfnresponse.SUCCESS
if event['RequestType'] == 'Create':
try:
...
cfnresponse.send(event, context, status, responseData, 'CustomResourcePhysicalID')

except Exception as e:
  status = cfnresponse.FAILED
  responseData['Error'] = str(e)
finally:
  cfnresponse.send(event, context, status, responseData, 'CustomResourcePhysicalID')       
```

**Comment by couchgott** [comment]
hey @jinseo-jang 

sounds pretty helpful. 
i will implement as soon as i find some time to do so :)

**Comment by couchgott** [comment]
it's now build-in
